name: finetuning
channels:
  - anaconda
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - cudatoolkit=11.3.1
  - pytorch=2.0.1
  - matplotlib=3.7.0
  - numpy=1.23.5
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - scipy=1.10.0
  - pip=23.0.1
  - tqdm=4.65.0
  - pip:
      - git+https://github.com/davidbau/baukit
      - einops==0.6.1
      - fire==0.5.0
      - peft==0.5.0
      - plotly==5.14.1
      - scikit-learn==1.2.2
      - sentencepiece==0.1.97
      - transformers==4.35.0
      - datasets==2.11.0